### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by Cisco-A** [proj-team-111/col_films#11]

**Comment by vinnyvics2** [comment]
**Typography, Checkbox, Colors, Grid System.**

https://www.figma.com/proto/IIWHRDB1XHrBQQnPiCI7jP/Proj-col_film-OneCube-team-library?node-id=412%3A4&scaling=scale-down&page-id=412%3A3

https://www.figma.com/proto/IIWHRDB1XHrBQQnPiCI7jP/Proj-col_film-OneCube-team-library?node-id=412%3A42&scaling=scale-down&page-id=412%3A3

https://www.figma.com/proto/IIWHRDB1XHrBQQnPiCI7jP/Proj-col_film-OneCube-team-library?node-id=422%3A8&scaling=scale-down&page-id=412%3A3

https://www.figma.com/proto/IIWHRDB1XHrBQQnPiCI7jP/Proj-col_film-OneCube-team-library?node-id=633%3A531&scaling=scale-down&page-id=412%3A3

https://www.figma.com/proto/IIWHRDB1XHrBQQnPiCI7jP/Proj-col_film-OneCube-team-library?node-id=412%3A7&scaling=scale-down&page-id=412%3A3

**Comment by ghost** [comment]
Input fields 

https://www.figma.com/proto/WoQiO8gAko6pzhVu5n7CH7/project_col_films?node-id=1%3A149&viewport=561%2C340%2C0.52&scaling=min-zoom&starting-point-node-id=2%3A248

**Comment by MrsJimray** [comment]
[[]](https://www.figma.com/file/IIWHRDB1XHrBQQnPiCI7jP/Proj-col_film-OneCube-team-library?node-id=412%3A42)(url)
color template/pallet
