### ISSUE TITLE
User research 

### ISSUE THREAD

**Issue by Cisco-A** [proj-team-111/col_films#12]

**Comment by hbeebs** [comment]
Here's the link

https://www.figma.com/file/yYuXwW9qO1S4RpiNgKiZg1/OneCube-Research?node-id=0%3A1

**Comment by Odunayomi23** [comment]
Here are the links

https://docs.google.com/document/d/1oBd4th1jO5UfFBgPVBH2FVQhtM2S8oiVtBkwQjTek3Q/edit?usp=sharing

https://www.figma.com/file/yYuXwW9qO1S4RpiNgKiZg1/OneCube-Research?node-id=0%3A1
