### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by Cisco-A** [proj-team-111/col_films#13]

**Comment by vinnyvics2** [comment]
**Authentication pages and Dashboard**

https://www.figma.com/proto/IIWHRDB1XHrBQQnPiCI7jP/Proj-col_film-OneCube-team-library?node-id=1833%3A4967&scaling=min-zoom&page-id=412%3A2

https://www.figma.com/proto/IIWHRDB1XHrBQQnPiCI7jP/Proj-col_film-OneCube-team-library?node-id=1833%3A5022&scaling=min-zoom&page-id=412%3A2

https://www.figma.com/proto/IIWHRDB1XHrBQQnPiCI7jP/Proj-col_film-OneCube-team-library?node-id=1833%3A5111&scaling=min-zoom&page-id=412%3A2

https://www.figma.com/proto/IIWHRDB1XHrBQQnPiCI7jP/Proj-col_film-OneCube-team-library?node-id=1833%3A5068&scaling=min-zoom&page-id=412%3A2

https://www.figma.com/proto/IIWHRDB1XHrBQQnPiCI7jP/Proj-col_film-OneCube-team-library?node-id=1833%3A5246&scaling=min-zoom&page-id=412%3A2

**Comment by ghost** [comment]
Landing page.

https://www.figma.com/proto/WoQiO8gAko6pzhVu5n7CH7/project_col_films?node-id=0%3A1&viewport=334%2C55%2C0.42&scaling=min-zoom&starting-point-node-id=1%3A15
