### ISSUE TITLE
Landing page Hi-fi

### ISSUE THREAD

**Issue by Cisco-A** [proj-team-111/col_films#15]

**Comment by hbeebs** [comment]
Here's the link to the prototype

https://www.figma.com/proto/IIWHRDB1XHrBQQnPiCI7jP/Proj-col_film-OneCube-team-library?page-id=1449%3A3431&node-id=1449%3A3449&starting-point-node-id=1449%3A3449&scaling=min-zoom&show-proto-sidebar=1

**Comment by Odunayomi23** [comment]
https://www.figma.com/proto/Gkmi6IJXbKrHw7ZAZAeD5l/Untitled?page-id=0%3A1&node-id=2%3A74&viewport=718%2C477%2C0.2&scaling=min-zoom&starting-point-node-id=2%3A74

**Comment by vinnyvics2** [comment]
**I worked on the hero section and the footer**

https://www.figma.com/proto/IIWHRDB1XHrBQQnPiCI7jP/Proj-col_film-OneCube-team-library?node-id=1449%3A3449&scaling=min-zoom&page-id=1449%3A3431&starting-point-node-id=1449%3A3449&show-proto-sidebar=1
