### ISSUE TITLE
Sign-up and sign-in hi-fi

### ISSUE THREAD

**Issue by Cisco-A** [proj-team-111/col_films#16]

**Comment by vinnyvics2** [comment]
https://www.figma.com/proto/IIWHRDB1XHrBQQnPiCI7jP/Proj-col_film-OneCube-team-library?node-id=1449%3A3436&scaling=min-zoom&page-id=1449%3A3431&starting-point-node-id=1449%3A3449&show-proto-sidebar=1

https://www.figma.com/proto/IIWHRDB1XHrBQQnPiCI7jP/Proj-col_film-OneCube-team-library?node-id=1449%3A3666&scaling=min-zoom&page-id=1449%3A3431&starting-point-node-id=1449%3A3449&show-proto-sidebar=1

https://www.figma.com/proto/IIWHRDB1XHrBQQnPiCI7jP/Proj-col_film-OneCube-team-library?node-id=1449%3A3685&scaling=min-zoom&page-id=1449%3A3431&starting-point-node-id=1449%3A3449&show-proto-sidebar=1

https://www.figma.com/proto/IIWHRDB1XHrBQQnPiCI7jP/Proj-col_film-OneCube-team-library?node-id=1449%3A3703&scaling=min-zoom&page-id=1449%3A3431&starting-point-node-id=1449%3A3449&show-proto-sidebar=1

https://www.figma.com/proto/IIWHRDB1XHrBQQnPiCI7jP/Proj-col_film-OneCube-team-library?node-id=1449%3A3831&scaling=min-zoom&page-id=1449%3A3431&starting-point-node-id=1449%3A3449&show-proto-sidebar=1

https://www.figma.com/proto/IIWHRDB1XHrBQQnPiCI7jP/Proj-col_film-OneCube-team-library?node-id=1449%3A3841&scaling=min-zoom&page-id=1449%3A3431&starting-point-node-id=1449%3A3449&show-proto-sidebar=1
