### ISSUE TITLE
Video Modal Page Design

### ISSUE THREAD

**Issue by proj-team-111** [proj-team-111/col_films#33]

**Comment by hbeebs** [comment]
Here's the link to the prototype

https://www.figma.com/proto/IIWHRDB1XHrBQQnPiCI7jP/Proj-col_film-OneCube-team-library?page-id=1449%3A3431&node-id=1551%3A4030&starting-point-node-id=1449%3A3449&scaling=min-zoom&show-proto-sidebar=1

**Comment by vinnyvics2** [comment]
**i worked on the Modal itself**

https://www.figma.com/proto/IIWHRDB1XHrBQQnPiCI7jP/Proj-col_film-OneCube-team-library?node-id=1551%3A4030&scaling=min-zoom&page-id=1449%3A3431&starting-point-node-id=1449%3A3449&show-proto-sidebar=1
