### ISSUE TITLE
Wire Frame and Lo-fi for Authentication

### ISSUE THREAD

**Issue by proj-team-111** [proj-team-111/col_films#37]

**Comment by Odunayomi23** [comment]
Here are the links to the responsive wireframe and lo-fi for authentification.

https://www.figma.com/proto/ODSu9oc8qg6JT7UTPGLTHO/Untitled?page-id=0%3A1&node-id=2%3A504&viewport=829%2C574%2C0.14&scaling=scale-down&starting-point-node-id=2%3A502

https://www.figma.com/proto/vVASvsDgwM7AryzWLviO5w/Untitled?page-id=0%3A1&node-id=2%3A226&viewport=718%2C509%2C0.36&scaling=min-zoom&starting-point-node-id=2%3A2
