### ISSUE TITLE
Library Screen Hi-fi

### ISSUE THREAD

**Issue by proj-team-111** [proj-team-111/col_films#43]

**Comment by Erieola** [comment]
**Web screen link**: https://www.figma.com/proto/dfZnMdglQ8nIKEaA8EukkG/Team-111_Proj-col_film_OneCube-Submission?page-id=1449%3A3431&node-id=1449%3A4661&viewport=414%2C400%2C0.03&scaling=scale-down-width&starting-point-node-id=1449%3A3449&show-proto-sidebar=1

**Mobile screen link**: https://www.figma.com/proto/dfZnMdglQ8nIKEaA8EukkG/Team-111_Proj-col_film_OneCube-Submission?page-id=1449%3A3431&node-id=1449%3A5174&viewport=414%2C400%2C0.03&scaling=scale-down-width&starting-point-node-id=1449%3A5086&show-proto-sidebar=1
