### ISSUE TITLE
Final Presentation Slides

### ISSUE THREAD

**Issue by proj-team-111** [proj-team-111/col_films#47]

**Comment by hbeebs** [comment]
this is the slides link

https://www.figma.com/proto/IIWHRDB1XHrBQQnPiCI7jP/Proj-col_film-OneCube-team-library?page-id=412%3A2&node-id=2151%3A9876&viewport=-1695%2C881%2C0.08&scaling=min-zoom&starting-point-node-id=2151%3A9876
