### ISSUE TITLE
Manage videos user journey 

### ISSUE THREAD

**Issue by Cisco-A** [proj-team-111/col_films#6]
https://docs.google.com/document/d/14_RsE2yjvEQ3J5-SVOfW0IsxWFp_ENuQ8p9IjQieT-E/edit?usp=sharing

**Comment by MrsJimray** [comment]
Manage Videos User Journey

[[]](https://docs.google.com/document/d/14_RsE2yjvEQ3J5-SVOfW0IsxWFp_ENuQ8p9IjQieT-E/edit?usp=sharing)(url)
